###  obteber todos los characters
GET http://localhost:3000/api/platos

###  obteber un character
GET http://localhost:3000/api/platos/b780c4c6-68c2-4177-2004-af0102a99d39



### modificar un character (PUT recurso completo e idempotente)
PATCH  http://localhost:3000/api/platos/b780c4c6-68c2-4177-2004-af0102a99d39
Content-Type: application/json

{
    "descripcion": "Fideos a la Bolonegsa",
    "tiempo": 20
}

### crear un nuevo character
POST http://localhost:3000/api/platos
Content-Type: application/json
    
{
    "platoClass": {
        "descripcion": "Plato Principal",
        "id": "b780c4c6-68c2-4177-8371-af0102a66d39"
    }, 
    "descripcion": "Milanesa",
    "tiempo": 35
}

### borrar info
DELETE http://localhost:3000/api/platos/0ec6ee25-e2dd-481c-8cc8-b4aa5dc83e96
