###Solicita todos los platos

GET http://localhost:3000/api/platos

###Solicita un plato en particular utilizando su numero de plato

GET http://localhost:3000/api/platos/3

###Ingresa un nuevo plato

POST http://localhost:3000/api/platos
Content-Type: application/json

{
  "descripcion": "Ñoquis con salsa bolognesa",
  "tiempo": 30,
  "precio": 3500,
  "aptoCeliacos": false,
  "aptoVegetarianos": false,
  "aptoVeganos": false,
  "tipoPlato": 2
}

###

POST http://localhost:3000/api/platos
Content-Type: application/json

{
  "descripcion": "Milanesa napolitana con papas fritas",
  "tiempo": 45,
  "precio": 5000,
  "aptoCeliacos": false,
  "aptoVegetarianos": false,
  "aptoVeganos": false,
  "tipoPlato": 2
}

###

POST http://localhost:3000/api/platos
Content-Type: application/json

{
  "descripcion": "Tiramisú",
  "tiempo": 5,
  "precio": 2500,
  "aptoCeliacos": true,
  "aptoVegetarianos": true,
  "aptoVeganos": false,
  "tipoPlato": 4
}

###

POST http://localhost:3000/api/platos
Content-Type: application/json

{
  "descripcion": "Arroz Primavera",
  "tiempo": 18,
  "precio": 2000,
  "aptoCeliacos": true,
  "aptoVegetarianos": true,
  "aptoVeganos": true,
  "tipoPlato": 2
}

###Modifica la descripción de un plato ya ingresado utilizando su código

PATCH http://localhost:3000/api/platos/5
Content-Type: application/json

{
  "descripcion": "Tiramisú",
  "tiempo": 5,
  "precio": 2500,
  "aptoCeliacos": true,
  "aptoVegetarianos": true,
  "aptoVeganos": false,
  "tipoPlato": 3
}

###Modifica la descripción de un plato ya ingresado utilizando su código

PATCH http://localhost:3000/api/platos/3
Content-Type: application/json

{
  "precio": 2800,
  "aptoCeliacos": false,
  "aptoVegetarianos": false,
  "aptoVeganos": false
}

###Elimina un plato existente utilizando su código

DELETE http://localhost:3000/api/platos/12
