###Solicita todos los platos

GET http://localhost:3000/api/platos

###Solicita un plato en particular utilizando su numero de plato

GET http://localhost:3000/api/platos/3

###Ingresa un nuevo plato

POST http://localhost:3000/api/platos
Content-Type: application/json

{
  "descripcion": "Ñoquis con Salsa Bolognesa",
  "tiempo": 20,
  "tipoPlato": 5
}

###

POST http://localhost:3000/api/platos
Content-Type: application/json

{
  "descripcion": "Milanesa napolitana",
  "tiempo": 25,
  "tipoPlato": 6
}

###Modifica la descripción de un plato ya ingresado utilizando su código

PATCH http://localhost:3000/api/platos/3
Content-Type: application/json

{
  "descripcion": "Ñoquis con Salsa Bolognesa"
}

###Elimina un plato existente utilizando su código

DELETE http://localhost:3000/api/platos/12
