### Solicita el total de tipos de plato
GET http://localhost:3000/api/platos/tipos

### Solicita un único tipo de plato según su código

GET http://localhost:3000/api/platos/tipos/4

### Ingresa un nuevo tipo de plato

POST http://localhost:3000/api/platos/tipos
Content-Type: application/json

{
  "descTPlato": "Entrada"
}

###

POST http://localhost:3000/api/platos/tipos
Content-Type: application/json

{
  "descTPlato": "Plato Principal"
}

###
POST http://localhost:3000/api/platos/tipos
Content-Type: application/json

{
  "descTPlato": "Postre"
}

### Modifica los atributos de un tipo de plato

PUT http://localhost:3000/api/platos/tipos/3
Content-Type: application/json

{
  "descTPlato": "Entrada"
}

### Borra un tipo de plato
DELETE http://localhost:3000/api/platos/tipos/2