###  obteber todos los characters
GET http://localhost:3000/api/platos/tipos


###  obteber un character
GET http://localhost:3000/api/platos/tipos/b780c4c6-68c2-4177-8371-af0102a66d39



### modificar un character (PUT recurso completo e idempotente)
PUT http://localhost:3000/api/platos/tipos/b780c4c6-68c2-4177-8371-af0102a66d39
Content-Type: application/json

{
    "descripcion": "Entrada"
}

### crear un nuevo character
POST http://localhost:3000/api/platos/tipos
Content-Type: application/json

{
    "descripcion": "Postre"
}

### borrar info
DELETE http://localhost:3000/api/platos/tipos/6777e183-e230-407c-b282-556e9f7f090b
