### Obtener todos los platos asociados a un ingrediente y sus cantidades

GET http://localhost:3000/api/pedidos/3/platos

### Obtener la cantidad para un ingrediente y un plato

GET http://localhost:3000/api/pedidos/3/platos/2?fechaSolicitud=2024-09-17&horaSolicitud=19:42

### Establecer una cantidad para un ingrediente dado un plato

POST http://localhost:3000/api/pedidos/3/platos
Content-Type: application/json

{
  "plato": 2,
  "cantidad": 1,
  "fechaSolicitud": "{{$localDatetime rfc1123}}",
  "horaSolicitud": "{{$localDatetime rfc1123}}",
  "entregado": false
}

### IDEM

POST http://localhost:3000/api/pedidos/3/platos
Content-Type: application/json

{
  "plato": 1,
  "cantidad": 1,
  "fechaSolicitud": "{{$localDatetime rfc1123}}",
  "horaSolicitud": "{{$localDatetime rfc1123}}",
  "entregado": false
}

### Modificar la cantidad de un ingrediente dado un plato

PATCH http://localhost:3000/api/pedidos/3/platos/1
Content-Type: application/json

{
  "entregado": true 
}

### IDEM

PATCH http://localhost:3000/api/pedidos/17/platos/3
Content-Type: application/json

{
  "cantidad": 54
}

### Eliminar la cantidad asociada a un ingrediente y un plato

DELETE http://localhost:3000/api/pedidos/14/platos/4

### IDEM

DELETE http://localhost:3000/api/pedidos/17/platos/3