### Obtener todos los platos asociados a un pedido y sus cantidades

GET http://localhost:3000/api/pedidos/1/platos

### Obtener un plato asociado a un pedido y su cantidad

GET http://localhost:3000/api/pedidos/1/platos/1

### Agregar un plato a un pedido
POST http://localhost:3000/api/pedidos/1/platos
Content-Type: application/json

{
  "plato": 1,
  "cantidad": 2
}

### Establecer un Plato de un Pedido como "entregado". Debe llegar la fecha, hora y cantidad del plato a entregar
PUT http://localhost:3000/api/pedidos/56/platos/16/fecha/2025-02-18/hora/01:35:08
Content-Type: application/json

{

}

### Eliminar un plato de un pedido

DELETE http://localhost:3000/api/pedidos/1/platos/1/fecha/2024-11-07/hora/17:01:34

### IDEM (DA ERROR INTENCIONALMENTE PORQUE YA FUE ENTREGADO)

DELETE http://localhost:3000/api/pedidos/1/platos/1/fecha/2024-11-07/hora/13:46:15