### Obtener todos los proveedores

GET http://localhost:3000/api/proveedores

### Obtener un único proveedor

GET http://localhost:3000/api/proveedores/20452157382

### Crear un nuevo proveedor

POST http://localhost:3000/api/proveedores
Content-Type: application/json

{
  "cuit": "1",
  "razonSocial": "HunKel S.A.",
  "direccion": "Dorrego 1265",
  "ciudad": "Venado Tuerto",
  "provincia": "Santa Fe",
  "pais": "Argentina",
  "telefono": "+54 9 3462 522974",
  "email": "contactHunkel@gmail.com"
}

### Crea un nuevo proveedor

POST http://localhost:3000/api/proveedores
Content-Type: application/json

{
  "cuit": "71452157228",
  "razonSocial": "TheoHad S.A.",
  "direccion": "Italia 738",
  "ciudad": "Venado Tuerto",
  "provincia": "Santa Fe",
  "pais": "Argentina",
  "telefono": "+54 9 3462 847219",
  "email": "contactTheitus@gmail.com"
}

###Modifica un proveedor 

PUT http://localhost:3000/api/proveedores/1
Content-Type: application/json

{

}

###Modifica un proveedor 

PATCH http://localhost:3000/api/proveedores/20452157382
Content-Type: application/json

{
  "cuit": "20452157382"
}

### Elimina un proveedor

DELETE http://localhost:3000/api/proveedores/1