### Obtener todos los proveedores

GET http://localhost:3000/api/proveedores

### Obtener un único proveedor

GET http://localhost:3000/api/proveedores/10

### Crear un nuevo proveedor

POST http://localhost:3000/api/proveedores
Content-Type: application/json

{
  "cuit": "20452157382",
  "razonSocial": "HunKel S.A.",
  "direccion": "Dorrego 1265",
  "ciudad": "Venado Tuerto",
  "provincia": "Santa Fe",
  "pais": "Argentina",
  "telefono": "+54 9 3462 522974",
  "email": "contactHunkel@gmail.com"
}

### Crea un nuevo proveedor

POST http://localhost:3000/api/proveedores
Content-Type: application/json

{
  "cuit": "71452157228",
  "razonSocial": "TheoHad S.A.",
  "direccion": "Italia 738",
  "ciudad": "Venado Tuerto",
  "provincia": "Santa Fe",
  "pais": "Argentina",
  "telefono": "+54 9 3462 522974",
  "email": "contactTheitus@gmail.com"
}

### Crea un nuevo proveedor (CON ERRORES)

POST http://localhost:3000/api/proveedores
Content-Type: application/json

{
  "cuit": "71452157982",
  "razonSocial": "Termos San Telmo",
  "direccion": "Italia 738",
  "ciudad": "Venado Tuerto",
  "provincia": "Santa Fe",
  "pais": "Argentina",
  "telefono": "+54 9 3462 847212",
  "email": "contactTheitis@gmail.com"
}

###Modifica un proveedor 

PUT http://localhost:3000/api/proveedores/1
Content-Type: application/json

{
  "cuit": "20452159982",
  "razonSocial": "HunKel S.A.",
  "direccion": "Dorrego 1265",
  "ciudad": "Venado Tuerto",
  "provincia": "Santa Fe",
  "pais": "Argentina",
  "telefono": "+54 9 3462 522974",
  "email": "contactHunkel@gmail.com"
}

###Modifica un proveedor 

PATCH http://localhost:3000/api/proveedores/1
Content-Type: application/json

{
  "cuit": "20452159982"
}

###Modifica un proveedor (CON ERROR)

PATCH http://localhost:3000/api/proveedores/1
Content-Type: application/json

{
  "cuit": "20452159982"
}

### Elimina un proveedor

DELETE http://localhost:3000/api/proveedores/3