###
GET http://localhost:3000/api/pedidos/9/bebidas

###
GET http://localhost:3000/api/pedidos/4/bebidas/1?fechaSolicitud=2024-09-05&horaSolicitud=00:51

###
POST http://localhost:3000/api/pedidos/1/bebidas
Content-Type: application/json

{
  "bebida": 3,
  "cantidad": 2
}
###
POST http://localhost:3000/api/pedidos/4/bebidas
Content-Type: application/json

{
  "bebida": 1,
  "fechaSolicitud": "2024-09-05",
  "horaSolicitud": "01:17",
  "cantidad": 1,
  "entregado": false
}
###
POST http://localhost:3000/api/pedidos/4/bebidas
Content-Type: application/json

{
  "bebida": 4,
  "fechaSolicitud": "2024-09-05",
  "horaSolicitud": "01:51",
  "cantidad": 1,
  "entregado": false
}
###
PUT http://localhost:3000/api/pedidos/1/bebidas/3
Content-Type: application/json

{
  "fechaSolicitud": "2024-11-07",
  "horaSolicitud": "09:57:09",
  "cantidad": 2
}
### Dado el ID del pedido, de la bebida y la fecha y hora de solicitud, eliminamos la bebida del pedido (si no fue entregada)
DELETE http://localhost:3000/api/pedidos/1/bebidas/3/fecha/2024-11-07/hora/10:00:28

### Dado el ID del pedido, de la bebida y la fecha y hora de solicitud, eliminamos la bebida del pedido (si no fue entregada)
DELETE http://localhost:3000/api/pedidos/1/bebidas/3/fecha/2024-11-07/hora/17:41:27