
###Solicita todos los ingredientes

GET http://localhost:3000/api/ingredientes

###Solicita un ingrediente en particular utilizando su código

GET http://localhost:3000/api/ingredientes/b780c456-68s2-4177-5371-af0102199j38

###Ingresa un nuevo ingrediente

POST http://localhost:3000/api/ingredientes
Content-Type: application/json

{
  "descIngrediente": "Papa",
  "stockIngrediente": 125,
  "puntoPedido": 40,
  "tipoIngrediente": "b780c4c6-68c2-4177-8371-af0102a99d38"
}

###Modifica la descripción de un ingrediente ya ingresado utilizando su código

PATCH http://localhost:3000/api/ingredientes/b780c456-68s2-4177-5371-af0102199j38
Content-Type: application/json

{
  "descIngrediente": "Calabaza Escocesa"
}

###Elimina un ingrediente existente utilizando su código

DELETE http://localhost:3000/api/ingredientes/b780c456-68s2-4177-5371-af0102199j38
