
###Solicita todos los ingredientes

GET http://localhost:3000/api/ingredientes

###Solicita un ingrediente en particular utilizando su código

GET http://localhost:3000/api/ingredientes/13

###Ingresa un nuevo ingrediente

POST http://localhost:3000/api/ingredientes
Content-Type: application/json

{
  "descIngre": "Queso Cremoso",
  "puntoDePedido": 7500,
  "unidadMedida": "gramos",
  "fechaVencimiento": "2024-08-22T10:30:00Z",
  "aptoCeliacos": true,
  "aptoVegetarianos": true,
  "aptoVeganos": false
}

###

POST http://localhost:3000/api/ingredientes
Content-Type: application/json

{
  "descIngre": "Pechuga de Pollo",
  "puntoDePedido": 2000,
  "unidadMedida": "gramos",
  "fechaVencimiento": "2024-08-22T17:40:00-03:00",
  "aptoCeliacos": true,
  "aptoVegetarianos": false,
  "aptoVeganos": false
}

###

POST http://localhost:3000/api/ingredientes
Content-Type: application/json

{
  "descIngre": "Sal Fina",
  "puntoDePedido": 2000,
  "unidadMedida": "gramos",
  "fechaVencimiento": "2024-08-22T17:40:00-03:00",
  "aptoCeliacos": true,
  "aptoVegetarianos": false,
  "aptoVeganos": false
}

###Modifica la descripción de un ingrediente ya ingresado utilizando su código

PATCH http://localhost:3000/api/ingredientes/1
Content-Type: application/json

{
  "descIngre": "Papas Fritas"
}

###Elimina un ingrediente existente utilizando su código

DELETE http://localhost:3000/api/ingredientes/15
