### FindAll IngreProv

GET http://localhost:3000/api/ingredientes/1/proveedores

### FindAll ProvIngre

GET http://localhost:3000/api/proveedores/2/ingredientes

### GetOne IngrePro

GET http://localhost:3000/api/ingredientes/1/proveedores/1

### GetOne ProvIngre

GET http://localhost:3000/api/proveedores/1/ingredientes/1

### Post IngrePro

POST http://localhost:3000/api/ingredientes/1/proveedores
Content-Type: application/json

{
  "proveedor": 1
}

### Post ProvIngre

POST http://localhost:3000/api/proveedores/2/ingredientes
Content-Type: application/json

{
  "ingrediente": 1
}

### Patch IngrePro (CONSULTAR CON EL EQUIPO SI PERMANECE ESTA FUNCIONALIDAD)

PATCH http://localhost:3000/api/ingredientes/1/proveedores/1
Content-Type: application/json

{
  "stock": 17500
}

### Patch ProvIngre (CONSULTAR CON EL EQUIPO SI PERMANECE ESTA FUNCIONALIDAD)

PATCH http://localhost:3000/api/proveedores/2/ingredientes/1
Content-Type: application/json

{
  "stock": 22500
}

### Delete IngrePro

DELETE http://localhost:3000/api/ingredientes/1/proveedores/1

### Delete ProvIngre

DELETE http://localhost:3000/api/proveedores/1/ingredientes/1

