
### Solicita el total de tipos de ingrediente
GET http://localhost:3000/api/tiposIngrediente

### Solicita un único tipo de ingrediente según su código

GET http://localhost:3000/api/tiposIngrediente/b780c4c6-68c2-4177-8371-af0102a99d38

### Ingresa un nuevo tipo de ingrediente

POST http://localhost:3000/api/tiposIngrediente
Content-Type: application/json

{
  "descripcion": "Fruta"
}

### Modifica los atributos de un tipo de ingrediente

PUT http://localhost:3000/api/tiposIngrediente/b780c4c6-68c2-4177-8371-af0102a99d38
Content-Type: application/json

{
  "descripcion": "Pasta"
}