###Solicita todos los clientes

GET http://localhost:3000/api/clientes

###Solicita un cliente en particular utilizando su id

GET http://localhost:3000/api/clientes/11

###Ingresa un nuevo cliente

POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "nombre": "Jorge",
  "apellido": "Kralje",
  "mail": "Jorege@gmail.com",
  "telefono": "132154154"
}

###

POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "nombre": "Levi",
  "apellido": "Ackerman",
  "mail": "Levi@gmail.com",
  "telefono": "132154154"
}

###

POST http://localhost:3000/api/clientes
Content-Type: application/json

{
  "nombre": "Tsuna",
  "apellido": "Sawada",
  "mail": "tsawada@gmail.com",
  "telefono": "810356281736"
}

###Modifica el mail de un cliente ya ingresado utilizando su código

PATCH http://localhost:3000/api/clientes/14
Content-Type: application/json

{
  "mail": "Ackerman@gmail.com"
}

###Elimina un cliente existente utilizando su código

DELETE http://localhost:3000/api/platos/12
