### FINDALL

GET http://localhost:3000/api/elaboracionesPlato

### FINDONE

GET http://localhost:3000/api/elaboracionesPlato/b780c456-68s2-4177-5371-af0102199j38.b780c4c6-68c2-4177-2004-af0102a99d39

### ADD

POST http://localhost:3000/api/elaboracionesPlato
Content-Type: application/json

{
  "ingrediente": {
    "codIngrediente": "b780c456-12s2-b177-5371-af0v02199f58",
    "descIngrediente": "Frutilla",
    "stockIngrediente": 75,
    "puntoPedido": 25,
    "tipoIngrediente": {
      "codigo": "b780c4c6-55c2-4177-8371-af0102a99d38",
      "descripcion": "Fruta",
      "medicionCantidad": "Gramos"
    }
  },
  "plato": {
    "nro": "b780c4c6-68c2-4177-2003-afh102a49e39",
    "platoClass": {
      "descripcion": "Postre",
      "id": "b780c4f8-68g1-4177-8371-af0102a66d39"
    },
    "descripcion": "Torta",
    "tiempo": 60
  },
  "cantIngreNecesaria": 375
}

### PATCH

PATCH http://localhost:3000/api/elaboracionesPlato/b780c456-68s2-4177-5371-af0102199j38.b780c4c6-68c2-4177-2004-af0102a99d39
Content-Type: application/json

{
  "cantIngreNecesaria": 450
}

### DELETE

DELETE http://localhost:3000/api/elaboracionesPlato/b780c456-12s2-b177-5371-af0v02199f58.b780c4c6-68c2-4177-2003-afh102a49e39