### Obtener todos los ingredientes y sus cantidades de un plato

GET http://localhost:3000/api/platos/4/ingredientes

### Obtener la cantidad para un ingrediente y un plato

GET http://localhost:3000/api/platos/3/ingredientes/13

### Establecer una cantidad para un ingrediente dado un plato

POST http://localhost:3000/api/platos/3/ingredientes
Content-Type: application/json

{
  "ingrediente": 13,
  "fechaVigencia": "16-08-2024",
  "cantidadNecesaria": 250
}

### IDEM

POST http://localhost:3000/api/platos/4/ingredientes
Content-Type: application/json

{
  "ingrediente": 17,
  "fechaVigencia": "2024-08-16",
  "cantidadNecesaria": 250
}

### Modificar la cantidad de un ingrediente dado un plato

PATCH http://localhost:3000/api/platos/3/ingredientes/13
Content-Type: application/json

{
  "cantidadNecesaria": 1050
}

### IDEM

PATCH http://localhost:3000/api/platos/4/ingredientes/14
Content-Type: application/json

{
  "CantidadNecesaria": 750
}

### Eliminar la cantidad asociada a un ingrediente y un plato

DELETE http://localhost:3000/api/platos/3/ingredientes/13

### IDEM

DELETE http://localhost:3000/api/platos/4/ingredientes/17