### Solicita TODOS los pedidos

GET http://localhost:3000/api/pedidos

### Solicita un ÚNICO pedido

GET http://localhost:3000/api/pedidos/1

### Crea un nuevo pedido V1

POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "estado": "En curso",
    "fecha": "{{$localDatetime rfc1123}}",
    "hora": "2024-08-26T19:28:00",
    "cliente": 4
}

### Crea un nuevo pedido V2

POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "estado": "En curso",
    "fecha": "{{$localDatetime rfc1123}}",
    "hora": "2024-08-26T19:31:00-03:00",
    "cliente": 1
}

###Modifica la descripción de un ingrediente ya ingresado utilizando su código

PATCH http://localhost:3000/api/pedidos/3
Content-Type: application/json

{
  "estado": "Finalizado"
}

###Elimina un ingrediente existente utilizando su código

DELETE http://localhost:3000/api/pedidos/2
