### Solicita TODOS los pedidos

GET http://localhost:3000/api/clientes/2/pedidos

### Solicita un ÚNICO pedido

GET http://localhost:3000/api/clientes/2/pedidos/1

### Crea un nuevo pedido V1

POST http://localhost:3000/api/clientes/2/pedidos
Content-Type: application/json

{
    "mesa": 2
}

### Crea un nuevo pedido V2

POST http://localhost:3000/api/clientes/2/pedidos
Content-Type: application/json

{
    "mesa": 2,
    "estado": "En CuRsO"
}

###Modifica la descripción de un ingrediente ya ingresado utilizando su código

PATCH http://localhost:3000/api/clientes/1/pedidos/1
Content-Type: application/json

{
  "estado": "Finalizado"
}

###Elimina un ingrediente existente utilizando su código

DELETE http://localhost:3000/api/clientes/2/pedidos/1
