# OBTENER TODOS LOS PEDIDOS #
GET http://localhost:3000/api/pedido

###

# OBTENER UN PEDIDO #
GET http://localhost:3000/api/pedido/d0c48218-7b5b-4796-8569-a6b24e638e9f

###

# NUEVO PEDIDO #
POST http://localhost:3000/api/pedido 
Content-Type: application/json

{
  "estado": "Libre",
  "fecha": "2023-07-28",
  "hora": "14:30",
  "nroMesa": 4,
  "cliente": {
    "nombre": "jose",
    "apellido": "pasto",
    "mail": "josepas@gmail.com",
    "telefono": 36346363,
    "codigo": "d0c48218-7b5b-4796-8569-a6b24e638e9f"}
}

###

# MODIFICAR PEDIDO (PUT) #
PUT http://localhost:3000/api/pedido/d0c48218-7b5b-4796-8569-a6b24e638e9f 
Content-Type: application/json

{
  "estado": "Ocupada",
  "fecha": "2023-07-15",
  "hora": "16:30",
  "nroMesa": 3
}

###

# MODIFICAR PEDIDO (PATCH) #
PATCH http://localhost:3000/api/pedido/d0c48218-7b5b-4796-8569-a6b24e638e9f 
Content-Type: application/json

{
  "hora": "19:30",
  "nroMesa": 6
}

###

# BORRAR PEDIDO #
DELETE http://localhost:3000/api/pedido/d0c48218-7b5b-4796-8569-a6b24e638e9f
