### Solicita TODOS los pedidos

GET http://localhost:3000/api/pedidos

### Solicita un ÚNICO pedido

GET http://localhost:3000/api/pedidos/1

### Crea un nuevo pedido V1

POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "estado": "En curso",
    "fecha": "{{$localDate rfc1123}}",
    "hora": "2024-08-26T19:28:00",
    "cliente": 1,
    "mesa": 2
}

### Crea un nuevo pedido V2

POST http://localhost:3000/api/pedidos
Content-Type: application/json

{
    "estado": "En curso",
    "fecha": "2024-09-05",
    "hora": "00:58",
    "cliente": 2,
    "mesa": 5
}

###Modifica la descripción de un ingrediente ya ingresado utilizando su código

PATCH http://localhost:3000/api/pedidos/2
Content-Type: application/json

{
  "estado": "Finalizado"
}

###Elimina un ingrediente existente utilizando su código

DELETE http://localhost:3000/api/pedidos/3
