### Solicita TODOS los pedidos

GET http://localhost:3000/api/clientes/21/pedidos

### Solicita un ÚNICO pedido

GET http://localhost:3000/api/clientes/pedidos/2

### Crea un nuevo pedido V1

POST http://localhost:3000/api/clientes/21/pedidos
Content-Type: application/json

{
    "mesa": 2
}

### Crea un nuevo pedido V2

POST http://localhost:3000/api/clientes/2/pedidos
Content-Type: application/json

{
    "mesa": 2
}

###Agrega platos y bebidas a un pedido en curso

PATCH http://localhost:3000/api/clientes/pedidos/10
Content-Type: application/json

{
  "platos": [
  {
    "numPlato": 17,
    "cantidad": 1
  }
  ],
  "bebidas": [
    {
      "codBebida": 2,
      "cantidad": 1
    }
  ]
}

###Agrega platos y bebidas a un pedido en curso

PATCH http://localhost:3000/api/clientes/pedidos/9
Content-Type: application/json

{
  "platos": [
  {
    "numPlato": 17,
    "cantidad": 1
  }
  ]
}

###Cancela un pedido

PATCH http://localhost:3000/api/clientes/pedidos/8
Content-Type: application/json

{
  "estado": "cancelado"
}

###Finaliza un pedido y genera el pago.

PUT http://localhost:3000/api/clientes/pedidos/1
Content-Type: application/json

{
  
}

###Elimina un ingrediente existente utilizando su código

DELETE http://localhost:3000/api/clientes/pedidos/1
