### Solicita el total reseñas
GET http://localhost:3000/api/resenas

### Solicita una unica reseña según su nro de pedido

GET http://localhost:3000/api/pedidos/9/resena

### Ingresa una nueva reseña para un pedido

POST http://localhost:3000/api/pedidos/18/resena
Content-Type: application/json

{
  "cuerpo": "Muy rico",
  "puntaje": 3
}

###

POST http://localhost:3000/api/pedidos/1/resena
Content-Type: application/json

{
  "fechaResena": "{{$localDatetime rfc1123}}",
  "cuerpo": "Horrible",
  "puntaje": 2
}

###
POST http://localhost:3000/api/pedidos/2/resena
Content-Type: application/json

{
  "fechaResena": "{{$localDatetime rfc1123}}",
  "cuerpo": "Aceptable",
  "puntaje": 6
}

### Modifica los atributos de una reseña

PUT http://localhost:3000/api/pedidos/18/resena
Content-Type: application/json

{
  "cuerpo": "Nefasto",
  "puntaje": 3
}

### Modifica los atributos de una reseña

PATCH http://localhost:3000/api/pedidos/18/resena
Content-Type: application/json

{
  "cuerpo": "Petón"
}

### Borra una reseña
DELETE http://localhost:3000/api/pedidos/1/resena