### Solicita TODAS las mesas

GET http://localhost:3000/api/mesas

### Solicita TODAS las mesas DISPONIBLES

GET http://localhost:3000/api/mesas?estado=Disponible

### Solicita una ÚNICA mesa (y genera el código para que el cliente pueda inicar su pedido)

GET http://localhost:3000/api/mesas/3

### Crea un nuevo pedido V1

POST http://localhost:3000/api/mesas
Content-Type: application/json

{
    "estado": "Disponible",
    "cantPersonasMax": 6
}

### Crea un nuevo pedido V2

POST http://localhost:3000/api/mesas
Content-Type: application/json

{
    "estado": "Disponible",
    "cantPersonasMax": 2
}

###Modifica la descripción de un ingrediente ya ingresado utilizando su código

PATCH http://localhost:3000/api/mesas/1
Content-Type: application/json

{
  "estado": "Ocupada"
}

###Modifica la descripción de un ingrediente ya ingresado utilizando su código

PATCH http://localhost:3000/api/mesas/1
Content-Type: application/json

{
  "estado": "Disponible"
}

###Elimina un ingrediente existente utilizando su código

DELETE http://localhost:3000/api/mesas/2
